### Feren Store: Shared information for apt modules

dewmpkgs = ["ubuntu-desktop", "kubuntu-desktop", "xubuntu-desktop", "lubuntu-desktop", "ubuntu-budgie-desktop", "ubuntu-gnome-desktop", "ubuntu-mate-desktop", "ubuntu-unity-desktop", "ubuntukylin-desktop", "ubuntustudio-desktop", #Upstream OS meta packages
        "kubuntu-settings-desktop", "budgie-desktop", "j4-dmenu-desktop", "matchbox-desktop", "mate-desktop", "neon-desktop", "neon-essentials-desktop", "vanilla-gnome-desktop", #Meta packages
        "gnome", "gnome-panel-control", "gnome-panel-data", "gnome-panel", "gnome-session-bin", "gnome-session-common", "gnome-session-flashback", "gnome-session-wayland", "gnome-session", "gnome-shell-common", "gnome-shell", "gnome-flashback-common", "gnome-flashback", "gnome-session-canberra", "gnome-settings-daemon-common", "gnome-settings-daemon-dev", "gnome-settings-daemon", #GNOME
        "mate-applets", "mate-desktop-common", "mate-desktop-environment-core", "mate-desktop-environment-extra", "mate-desktop-environment-extras", "mate-desktop-environment", "mate-desktop", "mate-panel-common", "mate-panel", "mate-session-manager", "mate-settings-daemon-common", "mate-settings-daemon-dev", "mate-settings-daemon", #MATE
        "xfce4-panel-dev", "xfce4-panel", "xfce4-session", "xfce4", "xfwm4", "xfwm4" #XFCE4
        "lxqt-core", "lxqt-panel", "lxqt-session", "lxqt", #LXQt
        "budgie-core", "budgie-core-dev", "budgie-desktop-environment", "budgie-desktop-doc", "budgie-desktop", #Budgie
        "unity-session", "unity", "unity-settings-daemon-dev", "unity-settings-daemon-schemas", "unity-settings-daemon", "unity-services", #Unity
        "enlightenment", "enlightenment-data", "enlightenment-dev", #Enlightenment
        "ukui-desktop-environment-core", "ukui-desktop-environment-extras", "ukui-desktop-environment", "ukui-menu", "ukui-menus", "ukui-panel", "ukui-sidebar", "ukui-window-switch", "ukui-session-manager", #UKUI
        "i3", "i3-wm", "dwm", "awesome", "xmonad", "openbox", "openbox-dev", "icewm-common", "icewm-experimental", "icewm-lite", "icewm", "ratpoison", "jwm", "fluxbox", "sway", "blackbox", "pekwm", "sawfish-data", "sawfish", "stumpwm", "9wm", "evilwm", "windowlab", "wm2", "afterstep", "afterstep-data", "amiwm", "xdm"] #Misc. WMs

communitypkgs = ["gnome-applets-data", "gnome-applets", "gnome-audio", "gnome-brave-icon-theme", "gnome-color-manager", "gnome-colors-common", "gnome-colors", "gnome-common", "gnome-control-center-data", "gnome-control-center-dev", "gnome-control-center-faces", "gnome-control-center", "gnome-core", "gnome-desktop-testing", "gnome-desktop3-data", "gnome-devel", "gnome-initial-setup", "gnome-menus", "gnome-mime-data", "gnome-packagekit-data", "gnome-packagekit", "gnome-pkg-tools", "gnome-platform-devel", "gnome-power-manager", "gnome-screensaver-flags", "gnome-screensaver", "gnome-shell-extensions", "gnome-software-common", "gnome-software-dev", "gnome-software-doc", "gnome-software-plugin-flatpak", "gnome-software-plugin-snap", "gnome-software", "gnome-startup-applications", "gnome-system-tools", "gnome-themes-extra-data", "gnome-themes-extra", "gnome-themes-standard", "gnome-themes-ubuntu", "gnome-tweak-tool", "gnome-tweaks", "gnome-user-guide", #GNOME
        "mate-applet-appmenu", "mate-applet-brisk-menu", "mate-applets-common", "mate-applets", "mate-control-center-common", "mate-control-center", "mate-dock-applet", "mate-equake-applet", "mate-indicator-applet-common", "mate-indicator-applet", "mate-menu", "mate-menus", "mate-netbook-common", "mate-netbook", "mate-notification-daemon-common", "mate-notification-daemon", "mate-power-manager-common", "mate-power-manager", "mate-screensaver-common", "mate-screensaver", "mate-sensors-applet-common", "mate-sensors-applet-nvidia", "mate-sensors-applet", "mate-sntray-plugin", "mate-tweak", "mate-utils-common", "mate-utils", #MATE
        "xfce4-appfinder", "xfce4-clipman", "xfce4-dev-tools", "xfce4-dev-tools", "xfce4-goodies", "xfce4-notifyd", "xfce4-panel-profiles", "xfce4-power-manager-data", "xfce4-power-manager-plugins", "xfce4-power-manager", "xfce4-screensaver", "xfce4-settings", "xfce4-terminal", "xfce4-volumed", "xfdesktop4-data", "xfdesktop4", "xfwm4-theme-breeze", #XFCE
        "lxqt-about", "lxqt-admin", "lxqt-branding-debian", "lxqt-build-tools", "lxqt-config", "lxqt-globalkeys", "lxqt-notificationd-l10n", "lxqt-notificationd", "lxqt-openssh-askpass", "lxqt-policykit", "lxqt-powermanagement", "lxqt-qtplugin", "lxqt-runner", "lxqt-sudo", "lxqt-system-theme", "lxqt-theme-debian", "lxqt-themes", #LXQt
        "budgie-extras-common", "budgie-extras-daemon", "budgie-lightdm-theme-base", "budgie-lightdm-theme", "budgie-previews", "budgie-quickchar", "budgie-wallstreet", "budgie-welcome", "budgie-window-shuffler", #Budgie
        "unity-china-video-scope", "unity-control-center-dev", "unity-control-center", "unity-greeter-badges", "unity-greeter", "unity-gtk-module-autopilot", "unity-gtk-module-common", "unity-gtk2-module", "unity-gtk3-module", "unity-lens-applications", "unity-lens-files", "unity-lens-music", "unity-lens-photos", "unity-lens-video", "unity-mail", "unity-schemas", "unity-scope-calculator", "unity-scope-devhelp", "unity-scope-gnote", "unity-scope-home", "unity-scope-launchpad", "unity-scope-manpages", "unity-scope-soundcloud", "unity-scope-tomboy", "unity-scope-video-remote", "unity-scope-virtualbox", "unity-scope-yahoostock", "unity-scope-zotero", "unity-scopes-master-default", "unity-scopes-runner", "unity-tweak-tool", #Unity
        "ukui-control-center", "ukui-greeter", "ukui-media-common", "ukui-media", "ukui-polkit", "ukui-power-manager-common", "ukui-power-manager", "ukui-screensaver", "ukui-settings-daemon-common", "ukui-settings-daemon-dev", "ukui-settings-daemon", "ukui-themes", #UKUI
        "dunst", "tint2", "lemonbar", "polybar"] #WM components
